<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.github.AbdullahAfifyKhalil</groupId>
    <artifactId>egy-names-parent</artifactId>
    <version>0.3.4</version>
    <packaging>pom</packaging>

    <name>Egyptian Names Parent</name>
    <description>Parent POM for Egyptian Names Java artifacts</description>
    <url>https://github.com/AbdullahAfifyKhalil/egy-names</url>

    <modules>
        <module>java/egy-names</module>
    </modules>
</project>
