name: egy_names
description: A production-grade Egyptian onomastic intelligence library for Dart and Flutter — generate, translate, annotate, split, and analyze Egyptian names.
version: 0.3.0
homepage: https://github.com/AbdullahAfifyKhalil/egy-names
repository: https://github.com/AbdullahAfifyKhalil/egy-names.git
issue_tracker: https://github.com/afify/egy-names/issues

environment:
  sdk: ^3.0.0

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
